Fixed Logo and fixed background, centered menu text, need to fix buttons.
This error is popping up.

  File "web.py", line 145, in turn
    phrase=phrase,
UnboundLocalError: local variable 'ph